///////////////////////////////////////////////////////////
//  MusicaService.cs
//  Implementation of the Class MusicaService
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2006 21:22:01
///////////////////////////////////////////////////////////


using System.Collections;
using Zonica.Interfaces.Services;
using Zonica.Model;

namespace Zonica.Services {
	public class MusicaService : Service, IMusicaService {
		/// <summary>
		/// Constructor default.
		/// </summary>
		public MusicaService() : base() {}

		~MusicaService() {}

		public override void Dispose() {}

		/// 
		/// <param name="idTemaMusical"></param>
		public TemaMusical RetrieveTemaMusical(int idTemaMusical) {
			return null;
		}

		/// 
		/// <param name="temaMusical"></param>
		public void SaveOrUpdateTemaMusical(TemaMusical temaMusical) {}

		/// 
		/// <param name="temaMusical"></param>
		public void DeleteTemaMusical(TemaMusical temaMusical) {}

		/// 
		/// <param name="artista"></param>
		public IList RetrieveTemasMusicalesByArtista(Artista artista) {
			return null;
		}

		/// 
		/// <param name="idArtista"></param>
		public Artista RetrieveArtista(int idArtista) {
			return null;
		}

		/// 
		/// <param name="artista"></param>
		public void SaveOrUpdateArtista(Artista artista) {}

		/// 
		/// <param name="artista"></param>
		public void DeleteArtista(Artista artista) {}

		public IList RetrieveAllArtistas() {
			return null;
		}

		/// 
		/// <param name="idEstiloMusical"></param>
		public EstiloMusical RetrieveEstiloMusical(int idEstiloMusical) {
			return null;
		}

		/// 
		/// <param name="estiloMusical"></param>
		public void DeleteEstiloMusical(EstiloMusical estiloMusical) {}

		/// 
		/// <param name="estiloMusical"></param>
		public void SaveOrUpdateEstiloMusical(EstiloMusical estiloMusical) {}

		/// 
		/// <param name="album"></param>
		public void SaveOrUpdateAlbum(Album album) {}

		/// 
		/// <param name="album"></param>
		public void DeleteAlbum(Album album) {}

		/// 
		/// <param name="idAlbum"></param>
		public Album RetrieveAlbum(int idAlbum) {
			return null;
		}

		/// 
		/// <param name="artista"></param>
		public IList RetrieveAlbumsByArtista(Artista artista) {
			return null;
		}

		/// 
		/// <param name="estiloMusical"></param>
		public IList RetrieveArtistasByEstiloMusical(EstiloMusical estiloMusical) {
			return null;
		}

		/// 
		/// <param name="templateArtista"></param>
		public IList BuscarArtistas(Artista templateArtista) {
			return null;
		}

	} //end MusicaService

} //end namespace Zonica.Services