///////////////////////////////////////////////////////////
//  EntidadBaseNombrada.cs
//  Implementation of the Class EntidadBaseNombrada
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2006 21:08:07
///////////////////////////////////////////////////////////
namespace Zonica.Model.BaseClasses {
	/// <summary>
	/// Entidad base de todas las entidades con nombre. Otorga a los implementadores
	/// las propiedades 'Nombre' y 'Id'.
	/// </summary>
	public abstract class EntidadBaseNombrada : EntidadBase {
		/// <summary>
		/// Nombre de la Entidad
		/// </summary>
		private string nombre;

		/// <summary>
		/// Constructor default.
		/// </summary>
		public EntidadBaseNombrada() : base() {}

		~EntidadBaseNombrada() {}

		public override void Dispose() {}

		/// <summary>
		/// Nombre de la Entidad
		/// </summary>
		public string Nombre {
			get { return nombre; }
			set { nombre = value; }
		}

	} //end EntidadBaseNombrada

} //end namespace BaseClasses