///////////////////////////////////////////////////////////
//  EntidadBase.cs
//  Implementation of the Class EntidadBase
//  Generated by Enterprise Architect
//  Created on:      04-Sep-2006 21:08:07
//  Original author: pgarcia
///////////////////////////////////////////////////////////

using System;


namespace Zonica.Model.BaseClasses {
	/// <summary>
	/// Entidad base para el sistema Zónica. Agrega a todos los que la extiendan la
	/// propiedad 'Id'.
	/// </summary>
	public abstract class EntidadBase {
		/// <summary>
		/// Id de la entidad
		/// </summary>
		private Int32 id;

		/// <summary>
		/// Constructor default.
		/// </summary>
		public EntidadBase() {}

		~EntidadBase() {}

		public virtual void Dispose() {}

		/// <summary>
		/// Obtiene/setea el Id de esta entidad.
		/// </summary>
		public Int32 Id {
			get { return id; }
			set { id = value; }
		}

	} //end EntidadBase

} //end namespace BaseClasses